# Generated by Django 5.2 on 2025-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_notes_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
