# Generated by Django 5.2 on 2025-05-04 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
