# Generated by Django 5.2 on 2025-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_period',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], max_length=10),
        ),
    ]
