# Generated by Django 5.2 on 2025-05-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
